title: Aniket Gupta - Portfolio
author: Aniket Gupta
email: aniketgupta11@hotmail.com
description: Aniket Gupta - Data Science, Machine Learning, Deep Learning, Data Visualisation
url: "https://anik8gupta.github.io"
github_username:  aik8gupta
#google_analytics: UA-110543961-1

theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
